# Change these first
owner: JonathanBout # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Portfolio
    url: https://jonathanbout.com
  - name: Astronomy Picture Of the Day
    url: https://apod.jonathanbout.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.jonathanbout.dev
  # baseUrl: /your-repo-name
  logoUrl: https://jonathanbout.dev/icon-dark.png
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This status page shows **real-time** statistics from a few websites I self-host. The status page itself is hosted using GitHub Actions and Pages, using a modified version of [upptime/upptime](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
