# Change these first
owner: JonathanBout # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Portfolio (.com)
    url: https://jonathanbout.com?changeLocale=true # changeLocale=true to make sure we don't do any redirects
    maxResponseTime: 3000
  - name: Portfolio (.nl)
    url: https://jonathanbout.nl?changeLocale=true
    maxResponseTime: 3000
  - name: Portfolio Backend
    url: https://jonathanbout.com/api/_health/first-party?simple=true # simple view is enough, we don't use all other data
    maxResponseTime: 3000
    __dangerous__body_degraded: degraded
    __dangerous__body_down: unhealthy
  - name: Astronomy Picture Of the Day
    url: https://apod.jonathanbout.com
    maxResponseTime: 3000
  - name: Content Delivery Server
    url: https://static.jonathanbout.dev/_cdn/server/health
    maxResponseTime: 3000

delay: 10000 # wait ten seconds between each request to prevent overloading the server

assignees:
  - JonathanBout

status-website:
  themeUrl: https://status.jonathanbout.dev/theme.css
  favicon: https://jonathanbout.dev/icon-dark.png
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.jonathanbout.dev
  # baseUrl: /your-repo-name
  logoUrl: https://jonathanbout.dev/icon-dark.png
  name: Status
  introTitle: ""
  introMessage: ""
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: "@JonathanBout"
      href: https://github.com/JonathanBout

workflowSchedule:
  uptime: "*/10 * * * *"
